### ISSUE TITLE
Enhancement request: Add `ssh` to images

### ISSUE THREAD

**Issue by felixfbecker** [PowerShell/PowerShell-Docker#374]
## Summary
For Ubuntu-based images, this just needs an `apt-get install openssh-client`.

## Steps to reproduce

```powershell
New-PSSession -HostName ... -UserName ... -KeyFilePath ...
```

## Expected behavior

Should allow PS remoting over SSH

## Actual behavior

Error:
```
Enter-PSSession: An error has occurred which PowerShell cannot handle. A remote session might have ended.
```
Digging into the `InnerException` reveals that it is because of missing `ssh`:

```
System.Management.Automation.CommandNotFoundException: The term 'ssh' is not recognized as the name of a cmdlet,
                              function, script file, or operable program.
                              Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
                                 at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes,
                              SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
                                 at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandOrigin commandOrigin,
                              ExecutionContext context)
                                 at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandOrigin commandOrigin)
                                 at System.Management.Automation.Runspaces.SSHConnectionInfo.StartSSHProcess(StreamWriter& stdInWriterVar,
                              StreamReader& stdOutReaderVar, StreamReader& stdErrReaderVar)
                                 at System.Management.Automation.Remoting.Client.SSHClientSessionTransportManager.CreateAsync()
                                 at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerImpl.SendNegotiationAsync(RemoteSessionState
                              sessionState)
                                 at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerImpl.HandleStateChanged(Object sender,
                              RemoteSessionStateEventArgs arg)
                                 at System.Management.Automation.ExtensionMethods.SafeInvoke[T](EventHandler`1 eventHandler, Object sender, T
                              eventArgs)
                                 at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerStateMachine.RaiseStateMachineEvents()
                                 at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerStateMachine.ProcessEvents()
```

For Ubuntu-based images, this just needs an `apt-get install openssh-client`.

## Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Linux 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by TravisEz13** [comment]
cc @RDIL Do you want to take this?

**Comment by RDIL** [comment]
I can't this week, sorry!

**Comment by TravisEz13** [comment]
@RDIL no problem

**Comment by coreone** [comment]
Is there any movement on this, potentially for *all* Linux-based images?  SSH appears to be the only protocol we can use to connect from Linux -> Windows with PowerShell.

**Comment by TravisEz13** [comment]
@coreone These images are intended to be base images.  Maintaining adding and maintaining SSH across all the images is a large amount of work. It's currently in the `community work` project, meaning it is not scheduled work.

cc @SteveL-MSFT

**Comment by kiazhi** [comment]
This work is mostly completed except for linux images on Arm32v7 architecture.

**Comment by TravisEz13** [comment]
Opened https://github.com/PowerShell/PowerShell-Docker/issues/474 to track the remaining work and closing this.
