### ISSUE TITLE
How to run as Administrator?

### ISSUE THREAD

**Issue by MichelDiz** [PowerShell/PowerShell-Docker#423]
## Steps to reproduce

The intention is to use this docker image to test an install script in a pipeline on every change.

```powershell

docker run -it mcr.microsoft.com/powershell:lts-nanoserver-1903

# inside the container
iwr 192.168.10.90:4507/install.ps1 -useb | iex
```

## Expected behavior

This step in the script needs to run as Admin, but it fails. There is a workaround for this?

## Actual behavior

Error running the script
```
INFO: Installing
Start-Process:
Line |
  44 |          Start-Process "$psHome\powershell.exe" -Verb runAs -ArgumentL …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The parameter '-Verb' is not supported for the cmdlet 'Start-Process' on this edition of PowerShell.
```

Trying with `--user ContainerAdministrator`

```
PS C:\>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new
### Environment
PSReadLine: 2.0.0
PowerShell: 7.0.0
OS: Microsoft Windows 10.0.18362
Last 0 Keys


### Exception

System.UnauthorizedAccessException: Access to the path 'PSReadLineHistoryFile_2319298988' is denied.
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancella
tionToken)

```

## Environment data

```sh
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 1
  Paused: 0
  Stopped: 3
 Images: 2
 Server Version: 19.03.8
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 18363 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Pro Version 1909 (OS Build 18363.418)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.848GiB
 Name: DESKTOP-67KLOQB
 ID: J4KN:GMY5:Q5KW:CREY:OBK6:3YA4:K4KY:KSOH:OZRO:PK2S:NXWO:2WSG
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 45
  System Time: 2020-05-14T01:50:18.5985502-03:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

```powershell
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by TravisEz13** [comment]
Use an image that supports users, such as windowsservercore.

**Comment by TravisEz13** [comment]
`ContainerAdministrator` is not a supported user for `nanoserver` per the windows team.  If you cannot accomplish, what you need as the default user, there is a bug in nanoserver.

**Comment by MichelDiz** [comment]
I was able to do it with
```
# escape=`
FROM mcr.microsoft.com/powershell:lts-nanoserver-1903
USER ContainerAdministrator

ENTRYPOINT [ "pwsh.exe" ]
```

But it would be very handy to have this as an option. There are scripts that need to be tested as Admin. And it is not possible to use `-Verb runAs`. Because we don't have access to UAC's UI.

```
Start-Process "pwsh" -Verb runAs -ArgumentList $scriptblock
```

**Comment by MichelDiz** [comment]
Also, windowsservercore won't work. And it is HUGE... that's not good for day to day use and storage space. 
```
docker run -it mcr.microsoft.com/powershell:windowsservercore --user ContainerAdministrator      C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: container 8bc078faf4d0d07413bab20fc90bf3bde00e71efab86541ff201ea61789eb868 encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: O sistema não pode encontrar o arquivo especificado. (0x2)
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000] extra info: {"CommandLine":"--user ContainerAdministrator","WorkingDirectory":"C:\\","Environment":{"PSCORE":"\"C:\\Program Files\\PowerShell\\latest\\pwsh.exe\""},"EmulateConsole":true,"CreateStdInPipe":true,"CreateStdOutPipe":true,"ConsoleSize":[30,120]}.
```

**Comment by TravisEz13** [comment]
@MiaRomero I'm sorry, but I cannot help you.  This is a problem with the underlying Windows container.  Please Open a Windows support or feature request.

**Comment by TravisEz13** [comment]
I added a known issues wiki and i'll update the readme to link to this soon:
https://github.com/PowerShell/PowerShell-Docker/wiki/Known-Issues
